export const database = {
  users: {
    id: 'uuid',
    email: 'varchar(255)',
    name: 'varchar(255)',
    avatar_url: 'text',
    created_at: 'timestamp with time zone',
    updated_at: 'timestamp with time zone',
  },
  workspaces: {
    id: 'uuid',
    name: 'varchar(255)',
    slug: 'varchar(255)',
    logo_url: 'text',
    created_by: 'uuid',
    created_at: 'timestamp with time zone',
    updated_at: 'timestamp with time zone',
  },
  workspace_members: {
    id: 'uuid',
    workspace_id: 'uuid',
    user_id: 'uuid',
    role: 'varchar(50)',
    joined_at: 'timestamp with time zone',
  },
  teams: {
    id: 'uuid',
    workspace_id: 'uuid',
    name: 'varchar(255)',
    key: 'varchar(10)',
    description: 'text',
    color: 'varchar(7)',
    created_at: 'timestamp with time zone',
    updated_at: 'timestamp with time zone',
  },
  team_members: {
    id: 'uuid',
    team_id: 'uuid',
    user_id: 'uuid',
    role: 'varchar(50)',
    joined_at: 'timestamp with time zone',
  },
  projects: {
    id: 'uuid',
    workspace_id: 'uuid',
    team_id: 'uuid',
    name: 'varchar(255)',
    description: 'text',
    status: 'varchar(50)',
    start_date: 'date',
    target_date: 'date',
    lead_id: 'uuid',
    created_at: 'timestamp with time zone',
    updated_at: 'timestamp with time zone',
  },
  cycles: {
    id: 'uuid',
    workspace_id: 'uuid',
    team_id: 'uuid',
    name: 'varchar(255)',
    number: 'integer',
    start_date: 'date',
    end_date: 'date',
    status: 'varchar(50)',
    created_at: 'timestamp with time zone',
    updated_at: 'timestamp with time zone',
  },
  issues: {
    id: 'uuid',
    identifier: 'varchar(20)',
    workspace_id: 'uuid',
    team_id: 'uuid',
    project_id: 'uuid',
    cycle_id: 'uuid',
    title: 'varchar(255)',
    description: 'text',
    status: 'varchar(50)',
    priority: 'varchar(20)',
    assignee_id: 'uuid',
    creator_id: 'uuid',
    estimate: 'integer',
    due_date: 'timestamp with time zone',
    completed_at: 'timestamp with time zone',
    created_at: 'timestamp with time zone',
    updated_at: 'timestamp with time zone',
  },
  labels: {
    id: 'uuid',
    workspace_id: 'uuid',
    name: 'varchar(100)',
    color: 'varchar(7)',
    created_at: 'timestamp with time zone',
  },
  issue_labels: {
    issue_id: 'uuid',
    label_id: 'uuid',
  },
  issue_comments: {
    id: 'uuid',
    issue_id: 'uuid',
    user_id: 'uuid',
    content: 'text',
    created_at: 'timestamp with time zone',
    updated_at: 'timestamp with time zone',
  },
  issue_history: {
    id: 'uuid',
    issue_id: 'uuid',
    user_id: 'uuid',
    action: 'varchar(50)',
    field_changed: 'varchar(100)',
    old_value: 'text',
    new_value: 'text',
    created_at: 'timestamp with time zone',
  },
}

export type Database = typeof database